// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Agent Profile Compiler contributors

import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  GENERATED_END_MARKER,
  GENERATED_START_MARKER,
  MANUAL_END_MARKER,
  MANUAL_START_MARKER,
  hasAllRegionMarkers,
  parseMixedFile,
} from "@agent-profile/compiler";

import {
  applyMigrationPlan,
  buildMigrationPlan,
} from "./migrationPlan";

async function createTempRoot(): Promise<string> {
  return mkdtemp(path.join(tmpdir(), "ap-migration-plan-"));
}

// The Phase 16 plan endpoint is now the same write-plan logic the CLI uses.
// Most regions/adoption tests therefore need a profile on disk so compile
// can produce generated bytes; without one, the plan refuses with
// requires-profile. This fixture writes a minimal valid profile that the
// compiler accepts.
const FIXTURE_PROFILE = `version: 1
profile:
  name: migration-plan-test
  description: Migration plan fixture.
stack:
  languages: [typescript]
  frameworks: [sveltekit]
  packageManagers: [npm]
  testing: []
clients:
  tabnine: { enabled: false }
  codex: { enabled: true }
  claude: { enabled: true }
workflow:
  sdd: true
  tdd: true
  finalReview: false
`;

async function writeFixtureProfile(root: string): Promise<void> {
  await writeFile(path.join(root, "ai-profile.yaml"), FIXTURE_PROFILE, "utf8");
}

test("preserve plan snapshot: zero writes, all rows resolved as preserve", async () => {
  const root = await createTempRoot();
  await writeFile(path.join(root, "AGENTS.md"), "manual body\n", "utf8");

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "preserve" },
    { path: "CLAUDE.md", action: "preserve" },
  ]);

  assert.equal(plan.writes.length, 0);
  assert.equal(plan.refusals.length, 0);
  assert.deepEqual(
    plan.resolved.map((r) => ({ path: r.path, action: r.action })),
    [
      { path: "AGENTS.md", action: "preserve" },
      { path: "CLAUDE.md", action: "preserve" },
    ],
  );
});

test("regions plan snapshot: existing AGENTS.md wrapped with compiled generated bytes", async () => {
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  await writeFile(path.join(root, "AGENTS.md"), "manual body\n", "utf8");

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "add-regions" },
  ]);

  assert.equal(plan.refusals.length, 0);
  assert.equal(plan.writes.length, 1);
  const write = plan.writes[0];
  assert.equal(write.path, "AGENTS.md");
  const buffer = Buffer.from(write.bytes);
  assert.ok(hasAllRegionMarkers(buffer), "all region markers present");
  const text = buffer.toString("utf8");
  assert.ok(text.includes(GENERATED_START_MARKER));
  assert.ok(text.includes(GENERATED_END_MARKER));
  assert.ok(text.includes(MANUAL_START_MARKER));
  assert.ok(text.includes(MANUAL_END_MARKER));
  const parsed = parseMixedFile(buffer);
  assert.equal(parsed.ok, true);
  if (parsed.ok) {
    // Manual region preserves the original bytes verbatim.
    assert.equal(parsed.manualInner.toString("utf8"), "manual body\n");
    // Generated region is non-empty now that we run real compile.
    assert.ok(parsed.generatedInner.length > 0);
  }
});

test("regions plan does not emit a write for a missing root file", async () => {
  // CLI parity: planRegionAdoptions skips when the on-disk file is absent.
  // The web plan must do the same instead of inventing an empty-region file.
  const root = await createTempRoot();
  await writeFixtureProfile(root);

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "add-regions" },
  ]);

  assert.equal(
    plan.writes.length,
    0,
    "missing file must not produce a synthesized write",
  );
  const refusal = plan.refusals.find((r) => r.path === "AGENTS.md");
  assert.equal(refusal?.reason, "missing-file");
});

test("regions plan refuses add-regions when ai-profile.yaml is absent", async () => {
  // Without a profile we cannot compile, so the regions adoption must
  // refuse with requires-profile instead of falling back to empty bytes.
  const root = await createTempRoot();
  await writeFile(path.join(root, "AGENTS.md"), "manual body\n", "utf8");

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "add-regions" },
  ]);

  assert.equal(plan.writes.length, 0);
  const refusal = plan.refusals.find((r) => r.path === "AGENTS.md");
  assert.equal(refusal?.reason, "requires-profile");
});

test("add-regions refuses with no-compiled-output when the profile does not emit that root", async () => {
  // A profile with Claude disabled does not produce CLAUDE.md. If the
  // user has an existing CLAUDE.md on disk and asks for add-regions,
  // the plan must refuse rather than silently insert an empty generated
  // region (which would blank out the section on the next compile).
  const root = await createTempRoot();
  const profileWithoutClaude = `version: 1
profile:
  name: no-claude
  description: Profile without claude.
stack:
  languages: [typescript]
  frameworks: []
  packageManagers: [npm]
  testing: []
clients:
  tabnine: { enabled: false }
  codex: { enabled: true }
  claude: { enabled: false }
workflow:
  sdd: false
  tdd: false
  finalReview: false
`;
  await writeFile(
    path.join(root, "ai-profile.yaml"),
    profileWithoutClaude,
    "utf8",
  );
  await writeFile(
    path.join(root, "CLAUDE.md"),
    "existing claude instructions\n",
    "utf8",
  );

  const plan = await buildMigrationPlan(root, [
    { path: "CLAUDE.md", action: "add-regions" },
  ]);

  assert.equal(
    plan.writes.length,
    0,
    "must not write when compile produced no bytes for this path",
  );
  const refusal = plan.refusals.find((r) => r.path === "CLAUDE.md");
  assert.equal(refusal?.reason, "no-compiled-output");
});

test("add-regions on an already-mixed file is idempotent (writes via replaceGeneratedRegion)", async () => {
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  // Properly-formed mixed file: blank line separates the two regions.
  const mixed = [
    "<!-- agent-profile:generated:start -->",
    "stale",
    "<!-- agent-profile:generated:end -->",
    "",
    "<!-- agent-profile:manual:start -->",
    "manual body",
    "<!-- agent-profile:manual:end -->",
    "",
  ].join("\n");
  await writeFile(path.join(root, "AGENTS.md"), mixed, "utf8");

  // add-regions on an already-mixed file flows through the shared
  // adoption helper, which calls replaceGeneratedRegion. The resulting
  // write is valid — adoption is idempotent with the compiled bytes.
  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "add-regions" },
  ]);
  assert.equal(plan.refusals.length, 0);
  assert.equal(plan.writes.length, 1);
  const updated = Buffer.from(plan.writes[0].bytes).toString("utf8");
  // Manual region must survive verbatim; stale generated body must be gone.
  assert.ok(updated.includes("manual body"));
  assert.equal(updated.includes("stale"), false);
});

test("regions plan refuses partial region markers (no silent overwrite)", async () => {
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  await writeFile(
    path.join(root, "AGENTS.md"),
    "<!-- agent-profile:generated:start -->\nbroken\n",
    "utf8",
  );

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "add-regions" },
  ]);

  assert.equal(plan.writes.length, 0);
  const refusal = plan.refusals.find((r) => r.path === "AGENTS.md");
  assert.equal(refusal?.reason, "partial-region-markers");
});

test("update-generated-region uses compiled bytes when ai-profile.yaml exists", async () => {
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  const mixed = [
    "<!-- agent-profile:generated:start -->",
    "stale generated body",
    "<!-- agent-profile:generated:end -->",
    "",
    "<!-- agent-profile:manual:start -->",
    "manual content",
    "<!-- agent-profile:manual:end -->",
    "",
  ].join("\n");
  await writeFile(path.join(root, "AGENTS.md"), mixed, "utf8");

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "update-generated-region" },
  ]);

  assert.equal(plan.refusals.length, 0);
  assert.equal(plan.writes.length, 1);
  const text = Buffer.from(plan.writes[0].bytes).toString("utf8");
  // Manual region must survive byte-for-byte.
  assert.ok(text.includes("manual content"));
  // Generated region must have been refreshed (no longer "stale").
  assert.equal(text.includes("stale generated body"), false);
});

test("update-generated-region refuses without ai-profile.yaml", async () => {
  const root = await createTempRoot();
  const mixed = [
    "<!-- agent-profile:generated:start -->",
    "<!-- agent-profile:generated:end -->",
    "<!-- agent-profile:manual:start -->",
    "manual",
    "<!-- agent-profile:manual:end -->",
    "",
  ].join("\n");
  await writeFile(path.join(root, "AGENTS.md"), mixed, "utf8");

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "update-generated-region" },
  ]);

  assert.equal(plan.writes.length, 0);
  const refusal = plan.refusals.find((r) => r.path === "AGENTS.md");
  assert.equal(refusal?.reason, "requires-profile");
});

test("replace-generated-owned without confirmReplace is refused", async () => {
  const root = await createTempRoot();
  const plan = await buildMigrationPlan(root, [
    { path: ".claude/settings.json", action: "replace-generated-owned" },
  ]);
  const refusal = plan.refusals.find((r) => r.path === ".claude/settings.json");
  assert.equal(refusal?.reason, "missing-replace-confirmation");
});

test("replace-generated-owned on root path is refused with ownership-mismatch", async () => {
  // The spec says Replace is never offered for root instructions; the
  // safe path there is update-generated-region. The plan endpoint
  // mirrors that rule.
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  const plan = await buildMigrationPlan(root, [
    {
      path: "AGENTS.md",
      action: "replace-generated-owned",
      confirmReplace: true,
    },
  ]);
  const refusal = plan.refusals.find((r) => r.path === "AGENTS.md");
  assert.equal(refusal?.reason, "ownership-mismatch");
});

test("replace-generated-owned without a matching lockfile ownership entry is refused", async () => {
  // Lockfile is absent → the row cannot be classified as generated-owned,
  // so replace must refuse with ownership-mismatch even when compile would
  // emit the file.
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  const plan = await buildMigrationPlan(root, [
    {
      path: ".claude/settings.json",
      action: "replace-generated-owned",
      confirmReplace: true,
    },
  ]);
  const refusal = plan.refusals.find((r) => r.path === ".claude/settings.json");
  assert.equal(refusal?.reason, "ownership-mismatch");
});

test("add-regions on an unsupported path is refused", async () => {
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  const plan = await buildMigrationPlan(root, [
    { path: ".mcp.json", action: "add-regions" },
  ]);
  assert.equal(plan.writes.length, 0);
  const refusal = plan.refusals.find((r) => r.path === ".mcp.json");
  assert.equal(refusal?.reason, "unsupported-path");
});

test("applyMigrationPlan writes the regions adoption to disk and parseMixedFile accepts the result", async () => {
  const root = await createTempRoot();
  await writeFixtureProfile(root);
  await writeFile(
    path.join(root, "AGENTS.md"),
    "# Title\n\nmanual body\n",
    "utf8",
  );

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "add-regions" },
  ]);
  const result = await applyMigrationPlan(root, plan);

  assert.equal(result.counts.change, 1);
  const onDisk = await readFile(path.join(root, "AGENTS.md"));
  assert.ok(hasAllRegionMarkers(onDisk));
  const parsed = parseMixedFile(onDisk);
  assert.equal(parsed.ok, true);
  if (parsed.ok) {
    assert.equal(
      parsed.manualInner.toString("utf8"),
      "# Title\n\nmanual body\n",
      "manual region must preserve original bytes verbatim",
    );
  }
});

test("preserve plan leaves disk bytes unchanged", async () => {
  const root = await createTempRoot();
  const before = "manual body\n";
  await writeFile(path.join(root, "AGENTS.md"), before, "utf8");

  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "preserve" },
  ]);
  await applyMigrationPlan(root, plan);

  const after = await readFile(path.join(root, "AGENTS.md"), "utf8");
  assert.equal(after, before);
});

test("skip action is treated as preserve (no write, no refusal)", async () => {
  const root = await createTempRoot();
  await writeFile(path.join(root, "AGENTS.md"), "x\n", "utf8");
  const plan = await buildMigrationPlan(root, [
    { path: "AGENTS.md", action: "skip" },
  ]);
  assert.equal(plan.writes.length, 0);
  assert.equal(plan.refusals.length, 0);
  const resolved = plan.resolved.find((r) => r.path === "AGENTS.md");
  assert.equal(resolved?.action, "skip");
});
