// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Agent Profile Compiler contributors

import { readFile } from "node:fs/promises";
import path from "node:path";

import {
  applyWritePlan,
  compileProfile,
  planRootInstructionsAdoption,
  planWrites,
  readLockfileForRegions,
  REGION_AWARE_ROOT_PATHS,
  safeOutputPath,
  type PlannedWrite,
  type RootInstructionsAdoption,
  type WritePlanResult,
} from "@agent-profile/compiler";
import { parseProfileYaml, type AiProfile } from "@agent-profile/core";

// Phase 16 contract: "UI uses the same import and write-plan logic as CLI."
// This module never executes its own region-merge logic. It loads the
// profile (when present), runs the compiler to produce generated bytes,
// then delegates to `planRootInstructionsAdoption` for the actual region
// adoption shape. Non-root paths flow through the same compile/lockfile
// path the CLI uses for `compile --write`, so the UI can only emit writes
// that the CLI itself would emit for the same inputs.

export type MigrationAction =
  | "preserve"
  | "add-regions"
  | "update-generated-region"
  | "replace-generated-owned"
  | "skip";

export type MigrationRowRequest = {
  path: string;
  action: MigrationAction;
  // Required for `replace-generated-owned`; ignored for every other action.
  confirmReplace?: boolean;
};

export type MigrationPlanRefusal = {
  path: string;
  reason:
    | "unsupported-path"
    | "missing-replace-confirmation"
    | "symlinked"
    | "partial-region-markers"
    | "duplicate-region-markers"
    | "requires-profile"
    | "no-compiled-output"
    | "missing-file"
    | "already-has-regions"
    | "ownership-mismatch"
    | "compile-failed";
  note: string;
};

export type MigrationPlanResult = {
  writes: PlannedWrite[];
  refusals: MigrationPlanRefusal[];
  resolved: Array<{ path: string; action: MigrationAction; bytes: number }>;
};

const REGION_ROOTS = new Set(REGION_AWARE_ROOT_PATHS);

export async function buildMigrationPlan(
  rootDir: string,
  rows: readonly MigrationRowRequest[],
): Promise<MigrationPlanResult> {
  // Load the profile and lockfile once per plan request. Both are optional —
  // a fresh repo has neither. Compile is skipped when the profile is missing.
  const profile = await readOptionalProfile(rootDir);
  const lockfile = await readLockfileForRegions(rootDir);

  // Run compile if a profile is present. If compile fails we surface a
  // refusal per affected row rather than swallowing the error.
  let compiledGeneratedByPath: Map<string, Uint8Array> | undefined;
  let compileError: string | undefined;
  if (profile) {
    const result = compileProfile({ profile });
    if (result.ok) {
      compiledGeneratedByPath = new Map();
      for (const f of result.files) {
        compiledGeneratedByPath.set(f.path, f.bytes);
      }
    } else {
      compileError = result.issues
        .map((issue) => `${issue.code}: ${issue.message}`)
        .join("; ");
    }
  }

  // Pre-compute root adoption outcomes once. Each row that asks for an
  // add-regions / update-generated-region / replace-generated-owned action on
  // a root path consults this map so root rows stay consistent with each
  // other even when the user mixes actions.
  const generatedBytesByRoot = new Map<string, Uint8Array>();
  if (compiledGeneratedByPath) {
    for (const root of REGION_ROOTS) {
      const bytes = compiledGeneratedByPath.get(root);
      if (bytes) generatedBytesByRoot.set(root, bytes);
    }
  }
  const rootAdoptions = await planRootInstructionsAdoption(
    rootDir,
    generatedBytesByRoot,
  );
  const rootOutcomeByPath = new Map<string, RootInstructionsAdoption>();
  for (const outcome of rootAdoptions) {
    rootOutcomeByPath.set(outcome.path, outcome);
  }

  // Lockfile ownership lookup for non-root rows (skills, subagents, client
  // config). Drives the `replace-generated-owned` and `update-generated-
  // region` action paths so the UI honours the same ownership labels the
  // CLI does.
  const ownershipByPath = new Map<
    string,
    "generated-owned" | "mixed" | "manual-owned"
  >();
  if (lockfile) {
    for (const output of lockfile.outputs) {
      ownershipByPath.set(output.path, output.ownership);
    }
  }

  const writes: PlannedWrite[] = [];
  const refusals: MigrationPlanRefusal[] = [];
  const resolved: MigrationPlanResult["resolved"] = [];

  for (const row of rows) {
    if (row.action === "skip" || row.action === "preserve") {
      resolved.push({ path: row.path, action: row.action, bytes: 0 });
      continue;
    }

    // The unsafe replace path requires an explicit per-row confirmation
    // regardless of what comes next.
    if (
      row.action === "replace-generated-owned" &&
      row.confirmReplace !== true
    ) {
      refusals.push({
        path: row.path,
        reason: "missing-replace-confirmation",
        note: "replace-generated-owned requires confirmReplace:true",
      });
      continue;
    }

    if (REGION_ROOTS.has(row.path)) {
      const outcome = rootOutcomeByPath.get(row.path);
      if (!outcome) {
        // Unreachable in practice because rootOutcomeByPath covers every
        // REGION_ROOTS entry, but we keep the defensive branch so a future
        // change to REGION_AWARE_ROOT_PATHS does not silently emit writes.
        refusals.push({
          path: row.path,
          reason: "unsupported-path",
          note: "no root outcome was computed for this path",
        });
        continue;
      }

      if (row.action === "add-regions") {
        if (!profile) {
          // Match CLI semantics: regions adoption only runs after a
          // profile exists and compile has produced generated bytes.
          // Refuse before invoking the shared helper rather than emitting
          // an empty generated region.
          refusals.push({
            path: row.path,
            reason: "requires-profile",
            note: "add-regions needs ai-profile.yaml so compile can emit the generated region",
          });
          continue;
        }
        if (compileError) {
          refusals.push({
            path: row.path,
            reason: "compile-failed",
            note: compileError,
          });
          continue;
        }
        applyRootOutcome(row, outcome, true, undefined, writes, refusals, resolved);
        continue;
      }

      if (row.action === "update-generated-region") {
        if (!profile) {
          refusals.push({
            path: row.path,
            reason: "requires-profile",
            note: "update-generated-region needs ai-profile.yaml; create one first",
          });
          continue;
        }
        if (compileError) {
          refusals.push({
            path: row.path,
            reason: "compile-failed",
            note: compileError,
          });
          continue;
        }
        if (!generatedBytesByRoot.has(row.path)) {
          refusals.push({
            path: row.path,
            reason: "no-compiled-output",
            note: `compile did not emit ${row.path}`,
          });
          continue;
        }
        // Update flows through the same shared adoption helper as add-
        // regions. The helper calls replaceGeneratedRegion when the file
        // already has markers and serializeMixedFile otherwise, which
        // matches the CLI's `compile --write` semantics for region-aware
        // root files.
        applyRootOutcome(row, outcome, true, undefined, writes, refusals, resolved);
        continue;
      }

      if (row.action === "replace-generated-owned") {
        // Root files are never classified as `generated-owned` in the
        // Phase 14 import report; the spec says Replace is "never offered
        // for `unknown`, `manual-owned`, or local runtime files." For
        // root paths the safe path is update-generated-region.
        refusals.push({
          path: row.path,
          reason: "ownership-mismatch",
          note: "replace-generated-owned is not available for root instructions; use update-generated-region",
        });
        continue;
      }
    }

    // Non-root rows: only `update-generated-region` and
    // `replace-generated-owned` are meaningful, and both require compiled
    // generated bytes + lockfile-asserted ownership.
    if (!profile) {
      refusals.push({
        path: row.path,
        reason: "requires-profile",
        note: "this action needs ai-profile.yaml; create one first",
      });
      continue;
    }
    if (compileError) {
      refusals.push({
        path: row.path,
        reason: "compile-failed",
        note: compileError,
      });
      continue;
    }
    const compiledBytes = compiledGeneratedByPath?.get(row.path);
    if (!compiledBytes) {
      refusals.push({
        path: row.path,
        reason: "no-compiled-output",
        note: `compile did not emit ${row.path}`,
      });
      continue;
    }

    if (row.action === "replace-generated-owned") {
      const ownership = ownershipByPath.get(row.path);
      if (ownership !== "generated-owned") {
        refusals.push({
          path: row.path,
          reason: "ownership-mismatch",
          note: `replace-generated-owned requires lockfile ownership=generated-owned (was ${ownership ?? "absent"})`,
        });
        continue;
      }
      writes.push({ path: row.path, bytes: compiledBytes });
      resolved.push({
        path: row.path,
        action: row.action,
        bytes: compiledBytes.length,
      });
      continue;
    }

    if (row.action === "update-generated-region") {
      const ownership = ownershipByPath.get(row.path);
      if (ownership !== "mixed") {
        refusals.push({
          path: row.path,
          reason: "ownership-mismatch",
          note: `update-generated-region requires lockfile ownership=mixed (was ${ownership ?? "absent"})`,
        });
        continue;
      }
      // Mixed non-root files are not currently produced by compile, so we
      // refuse with the same shape until a later phase extends the
      // compiler to emit mixed non-root outputs.
      refusals.push({
        path: row.path,
        reason: "no-compiled-output",
        note: "compile does not emit mixed outputs for non-root paths yet",
      });
      continue;
    }

    if (row.action === "add-regions") {
      refusals.push({
        path: row.path,
        reason: "unsupported-path",
        note: "add-regions is only valid for AGENTS.md and CLAUDE.md",
      });
      continue;
    }
  }

  return { writes, refusals, resolved };
}

function applyRootOutcome(
  row: MigrationRowRequest,
  outcome: RootInstructionsAdoption,
  profileLoaded: boolean,
  compileError: string | undefined,
  writes: PlannedWrite[],
  refusals: MigrationPlanRefusal[],
  resolved: MigrationPlanResult["resolved"],
): void {
  if (!outcome.ok) {
    switch (outcome.reason) {
      case "symlink":
        refusals.push({
          path: outcome.path,
          reason: "symlinked",
          note: "Phase 14 refuses to follow symlinks",
        });
        return;
      case "partial-markers":
        refusals.push({
          path: outcome.path,
          reason: "partial-region-markers",
          note: "file has partial region markers and must be repaired manually",
        });
        return;
      case "duplicate-markers":
        refusals.push({
          path: outcome.path,
          reason: "duplicate-region-markers",
          note: "file has duplicate generated markers; cannot safely replace",
        });
        return;
      case "missing-file":
        refusals.push({
          path: outcome.path,
          reason: "missing-file",
          note: "file does not exist on disk; nothing to adopt",
        });
        return;
      case "missing-generated-bytes":
        refusals.push({
          path: outcome.path,
          reason: profileLoaded
            ? compileError
              ? "compile-failed"
              : "no-compiled-output"
            : "requires-profile",
          note: profileLoaded
            ? compileError ?? `compile did not emit ${outcome.path}`
            : "ai-profile.yaml is missing; cannot insert a generated region",
        });
        return;
    }
  }

  writes.push({ path: outcome.path, bytes: outcome.bytes });
  resolved.push({
    path: row.path,
    action: row.action,
    bytes: outcome.bytes.length,
  });
}

export async function applyMigrationPlan(
  rootDir: string,
  plan: MigrationPlanResult,
): Promise<WritePlanResult> {
  return applyWritePlan({ rootDir, writes: plan.writes });
}

export async function previewMigrationPlan(
  rootDir: string,
  plan: MigrationPlanResult,
): Promise<WritePlanResult> {
  return planWrites({ rootDir, writes: plan.writes });
}

export function isContainedPath(rootDir: string, relativePath: string): boolean {
  try {
    const resolved = path.resolve(
      rootDir,
      ...safeOutputPath(relativePath).split("/"),
    );
    return resolved.startsWith(path.resolve(rootDir) + path.sep);
  } catch {
    return false;
  }
}

async function readOptionalProfile(rootDir: string): Promise<AiProfile | undefined> {
  let source: string;
  try {
    source = await readFile(path.join(rootDir, "ai-profile.yaml"), "utf8");
  } catch (err) {
    if (
      typeof err === "object" &&
      err !== null &&
      "code" in err &&
      (err as { code?: string }).code === "ENOENT"
    ) {
      return undefined;
    }
    throw err;
  }
  const parsed = parseProfileYaml(source);
  return parsed.ok ? parsed.profile : undefined;
}
