// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Agent Profile Compiler contributors

export {
  ADVISORY_HOOK_ROLE_IDS,
  assertNoRemoteRefs,
  compileProfileSchema,
  DEFAULT_SUBAGENT_MAX_CONCURRENT,
  DEFAULT_SUBAGENT_MAX_DEPTH,
  DEFAULT_SUBAGENT_POLICY_ROLES,
  deriveEffectivePermissions,
  expandSubagentEntry,
  getEffectiveSubagentPolicyRoles,
  resolveEffectiveSubagentPolicy,
  getEnabledSubagents,
  getRemoteRefs,
  getSelectedAdvisoryHookRoles,
  getSubagentDefaults,
  getSubagentTemplate,
  getSubagentTemplateRefs,
  isSubagentBuiltinNameCollision,
  isSubagentTemplateRef,
  normalizeSafety,
  normalizeSubagentName,
  parseProfileYaml,
  readProfileFile,
  renderProfileYaml,
  SUBAGENT_POLICY_MAX_CONCURRENT_THREADS,
  SUBAGENT_POLICY_MAX_DEPTH,
  SUBAGENT_POLICY_RETENTION_MAX,
  SUBAGENT_POLICY_ROLE_IDS,
  SUBAGENT_POLICY_TARGET_MAPPING_VERSION,
  SUBAGENT_POLICY_TARGET_MODELS,
  SUBAGENT_TEMPLATE_NAMES,
  validateProfileValue,
} from "./profile.js";
export { resolvePermissionPosture } from "./permission-posture.js";
export type {
  ClientPosturePlan,
  HardDenials,
  PermissionPosture,
  PermissionPostureClientId,
  PermissionPostureLegacyStatus,
  PermissionPosturePlan,
} from "./permission-posture.js";
export { containsSecretLikeLiteral } from "./security.js";
export { REVIEWER_DEFINITIONS } from "./reviewer-definitions.js";
export type { ReviewerDefinition } from "./reviewer-definitions.js";
export {
  CAPABILITY_CATALOG,
  CAPABILITY_CATALOG_VERSION,
  computeOfferedCapabilities,
} from "./capability-catalog.js";
export type {
  CapabilityCatalogEntry,
  CapabilityInsertionShape,
  UpgradeableWorkflowField,
} from "./capability-catalog.js";
export { PRESET_VERIFICATION_KEYS } from "./preset/public-keys.js";
export { verifyPresetToken } from "./preset/token.js";
export type { PresetVerificationKey } from "./preset/public-keys.js";
export type {
  PresetPermissionMode,
  PresetPreferences,
  PresetSafetyMode,
  PresetTokenError,
  PresetTokenErrorCode,
  PresetTokenPayloadV1,
  PresetTokenProtectedHeader,
  PresetVerificationResult,
  VerifyPresetTokenOptions,
} from "./preset/token.js";
export type {
  AiProfile,
  AiProfileAdvisoryHookRoleId,
  AiProfileCapabilities,
  AiProfileClient,
  AiProfileClients,
  AiProfileEffectivePermissions,
  AiProfileHooks,
  AiProfilePermissions,
  AiProfileSafety,
  AiProfileSkillPackId,
  AiProfileSkills,
  AiProfileStack,
  AiProfileSubagent,
  AiProfileSubagentEntry,
  AiProfileSubagentPackId,
  AiProfileSubagentPolicy,
  ClientPermissionPosture,
  EffectiveSubagentPolicy,
  EffectiveSubagentPolicyRole,
  AiProfileSubagentTemplateRef,
  AiProfileSubagents,
  NormalizedAiProfileSafety,
  NormalizedSubagentDefaults,
  PermissionMode,
  ProfileValidationIssue,
  ProfileValidationIssueCode,
  ProfileValidationResult,
  SafetyMode,
  SubagentModelPreference,
  SubagentPolicyCapability,
  SubagentPolicyClaudeModel,
  SubagentPolicyClaudeRoleOverride,
  SubagentPolicyCodexModel,
  SubagentPolicyCodexRoleOverride,
  SubagentPolicyContext,
  SubagentPolicyEffort,
  SubagentPolicyEvidence,
  SubagentPolicyIndexedMode,
  SubagentPolicyIndexedProvider,
  SubagentPolicyOrchestration,
  SubagentPolicyOverrideTarget,
  SubagentPolicyRole,
  SubagentPolicyRoleId,
  SubagentPolicyRoleOverride,
  SubagentPolicyRoleOverrides,
  SubagentPolicyRoles,
  SubagentTemplateName,
  SubagentToolScope,
} from "./profile.js";
