// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Agent Profile Compiler contributors

import { CODE_REVIEW_TOPIC } from "./guidance-content.js";
import {
  REVIEWER_DEFINITIONS,
  type ReviewerDefinition,
} from "@agent-profile/core";
import type { SkillId } from "./skill-selection.js";

function renderBullets(items: readonly string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}

export function renderReviewChangeSkill(
  selectedSkills: ReadonlySet<SkillId>,
): string {
  const sections = CODE_REVIEW_TOPIC.subsections
    .map(
      (section) => `## ${section.heading}\n\n${renderBullets(section.bullets)}`,
    )
    .join("\n\n");
  const specialists = REVIEWER_DEFINITIONS.filter((definition) =>
    selectedSkills.has(definition.skillId),
  );
  const specialistSection =
    specialists.length === 0
      ? ""
      : `\n\n## Specialist Reviews\n\n${specialists
          .map(
            (definition) =>
              `- For a deeper pass, run \`${definition.skillId}\`.`,
          )
          .join("\n")}`;

  return `---
name: review-change
description: Use to review a proposed change for correctness, security-sensitive behavior, readability, tests, performance when relevant, architecture and contract impact, and generated-file drift.
---

<!-- Generated by Agent Profile Compiler. Do not edit by hand. -->

# Review Change

${CODE_REVIEW_TOPIC.intro}

${sections}${specialistSection}

## Safety

- Review only; do not rewrite or apply patches unless the user asks.
- Do not upload source code or read or print secrets.
- Do not install dependencies, contact production systems, or broaden permissions.
`;
}

function renderSpecialistSkill(definition: ReviewerDefinition): string {
  return `---
name: ${definition.skillId}
description: ${definition.description}
---

<!-- Generated by Agent Profile Compiler. Do not edit by hand. -->

# ${definition.title}

## Focus

${renderBullets(definition.focus)}

## Output Discipline

- Lead with prioritized findings and concrete evidence.
- Cite the affected file, symbol, or contract when available.
- Distinguish confirmed defects from risks or missing evidence.
- Do not edit or rewrite the change unless the user asks.

## Safety

- Review only; do not run scanners, install tools, or broaden permissions.
- Do not upload source code or read or print secrets.
- Do not contact production systems or external services.
`;
}

export function renderSpecialistReviewSkill(
  skill: SkillId,
): string | undefined {
  const definition = REVIEWER_DEFINITIONS.find(
    (candidate) => candidate.skillId === skill,
  );
  return definition === undefined
    ? undefined
    : renderSpecialistSkill(definition);
}

export function renderMcpFitCheckSkill(): string {
  return `---
name: mcp-fit-check
description: Use to assess whether current documentation through an MCP, docs, or search integration may help with a dependency that may be newer than the client's knowledge.
---

<!-- Generated by Agent Profile Compiler. Do not edit by hand. -->

# MCP Fit Check

## Assessment

1. Identify the dependency, framework, runtime, or SDK whose current behavior matters.
2. Explain why it may be newer than the client's knowledge; never claim the model definitely lacks that knowledge.
3. Recommend only the type of current documentation integration that may help and explain its risk.
4. Keep the result informational and defer every install or configuration decision to the user.

## Boundaries

- Never install or configure an MCP server, documentation connector, or search integration.
- Do not generate MCP configuration, server commands, install commands, environment variable names, tokens, or arbitrary MCP ids.
- Do not make network calls, execute commands, or change files.
- Do not read or print secrets.

## Output

Report the dependency, why current docs may help, the recommended integration category, its risk, and the explicit next decision for the user.
`;
}
