// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Agent Profile Compiler contributors

import { sha256Hex } from "./shared.js";

export const GENERATED_START_MARKER = "<!-- agent-profile:generated:start -->";
export const GENERATED_END_MARKER = "<!-- agent-profile:generated:end -->";
export const MANUAL_START_MARKER = "<!-- agent-profile:manual:start -->";
export const MANUAL_END_MARKER = "<!-- agent-profile:manual:end -->";

export const REGION_PRECEDENCE_TEXT =
  "If generated and manual instructions conflict, follow the manual project instructions unless they would weaken safety, privacy, or permission limits. Safety, privacy, and explicit deny rules always win.";

export const LEGACY_GENERATED_MARKER =
  "<!-- Generated by Agent Profile Compiler. Do not edit by hand. -->";

export type RegionOwnership =
  | "generated-owned"
  | "mixed"
  | "manual-owned"
  | "unknown";

export type RegionParseIssueCode =
  | "missing-markers"
  | "duplicate-markers"
  | "out-of-order"
  | "extra-bytes"
  | "preamble"
  | "missing-blank-line"
  | "missing-trailing-newline";

export type RegionParseIssue = {
  code: RegionParseIssueCode;
  message: string;
};

export type ParsedRegions =
  | {
      ok: true;
      generatedInner: Buffer;
      manualInner: Buffer;
      generatedInnerHash: string;
    }
  | {
      ok: false;
      issues: RegionParseIssue[];
    };

const GENERATED_START_RE = /^<!-- agent-profile:generated:start -->$/u;
const GENERATED_END_RE = /^<!-- agent-profile:generated:end -->$/u;
const MANUAL_START_RE = /^<!-- agent-profile:manual:start -->$/u;
const MANUAL_END_RE = /^<!-- agent-profile:manual:end -->$/u;

/**
 * Parse a mixed-ownership instruction file (AGENTS.md or CLAUDE.md) into its
 * generated and manual regions. Raw bytes are preserved; no normalization is
 * applied so that hashes match the on-disk content exactly.
 *
 * The Phase 14 spec defines a strict file shape: the file begins with the
 * generated start marker, the two regions are separated by exactly one blank
 * line, and the file ends with the manual end marker plus a single trailing
 * newline. Markers that appear inside fenced code blocks (``` ... ```) are
 * not counted as region markers.
 */
export function parseMixedFile(bytes: Buffer): ParsedRegions {
  const text = bytes.toString("utf8");
  const lineEndings: string[] = [];
  const lines: string[] = [];

  let position = 0;
  while (position < text.length) {
    const newlineIndex = text.indexOf("\n", position);

    if (newlineIndex === -1) {
      lines.push(text.slice(position));
      lineEndings.push("");
      break;
    }

    let lineEnd = newlineIndex;
    let ending = "\n";

    if (lineEnd > position && text[lineEnd - 1] === "\r") {
      lineEnd = newlineIndex - 1;
      ending = "\r\n";
    }

    lines.push(text.slice(position, lineEnd));
    lineEndings.push(ending);
    position = newlineIndex + 1;
  }

  const inFence = computeCodeFenceMask(lines);
  const matches = {
    generatedStart: [] as number[],
    generatedEnd: [] as number[],
    manualStart: [] as number[],
    manualEnd: [] as number[],
  };

  lines.forEach((line, index) => {
    if (inFence[index]) return;
    if (GENERATED_START_RE.test(line)) matches.generatedStart.push(index);
    if (GENERATED_END_RE.test(line)) matches.generatedEnd.push(index);
    if (MANUAL_START_RE.test(line)) matches.manualStart.push(index);
    if (MANUAL_END_RE.test(line)) matches.manualEnd.push(index);
  });

  const issues: RegionParseIssue[] = [];

  if (
    matches.generatedStart.length > 1 ||
    matches.generatedEnd.length > 1 ||
    matches.manualStart.length > 1 ||
    matches.manualEnd.length > 1
  ) {
    issues.push({
      code: "duplicate-markers",
      message:
        "Mixed instruction file contains duplicate generated/manual region markers.",
    });
    return { ok: false, issues };
  }

  if (
    matches.generatedStart.length !== 1 ||
    matches.generatedEnd.length !== 1 ||
    matches.manualStart.length !== 1 ||
    matches.manualEnd.length !== 1
  ) {
    issues.push({
      code: "missing-markers",
      message:
        "Mixed instruction file is missing one or more required region markers.",
    });
    return { ok: false, issues };
  }

  const gs = matches.generatedStart[0]!;
  const ge = matches.generatedEnd[0]!;
  const ms = matches.manualStart[0]!;
  const me = matches.manualEnd[0]!;

  if (!(gs < ge && ge < ms && ms < me)) {
    issues.push({
      code: "out-of-order",
      message:
        "Mixed instruction file region markers must appear in generated-start, generated-end, manual-start, manual-end order.",
    });
    return { ok: false, issues };
  }

  if (gs !== 0) {
    issues.push({
      code: "preamble",
      message:
        "Mixed instruction file must begin with the generated start marker; no preamble bytes are allowed.",
    });
    return { ok: false, issues };
  }

  // Exactly one blank line between the generated end marker and the manual
  // start marker.
  if (ms !== ge + 2 || (lines[ge + 1] ?? "") !== "") {
    issues.push({
      code: "missing-blank-line",
      message:
        "Mixed instruction file must have exactly one blank line between the generated and manual regions.",
    });
    return { ok: false, issues };
  }

  // Exactly one trailing newline after the manual end marker. The line
  // splitter emits one entry per line, with the marker as the final line and
  // its lineEnding "\n" (or "\r\n") representing the trailing newline.
  const trailingOk =
    lines.length === me + 1 && (lineEndings[me] ?? "").length > 0;

  if (!trailingOk) {
    issues.push({
      code: "missing-trailing-newline",
      message:
        "Mixed instruction file must end with the manual end marker followed by exactly one trailing newline.",
    });
    return { ok: false, issues };
  }

  const generatedInnerBytes = computeRangeBytes(bytes, lines, lineEndings, gs, ge);
  const manualInnerBytes = computeRangeBytes(bytes, lines, lineEndings, ms, me);

  return {
    ok: true,
    generatedInner: generatedInnerBytes,
    manualInner: manualInnerBytes,
    generatedInnerHash: sha256Hex(generatedInnerBytes),
  };
}

function computeCodeFenceMask(lines: string[]): boolean[] {
  const mask = new Array<boolean>(lines.length).fill(false);
  let open = false;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (/^\s{0,3}(?:```|~~~)/u.test(line)) {
      // The opening or closing fence line is itself inside the fence.
      mask[index] = open || true;
      open = !open;
      continue;
    }
    mask[index] = open;
  }
  return mask;
}

function computeRangeBytes(
  bytes: Buffer,
  lines: string[],
  lineEndings: string[],
  startMarkerIndex: number,
  endMarkerIndex: number,
): Buffer {
  // Bytes strictly between the marker lines: starts after the line ending
  // that follows the start marker; ends just before the end marker line.
  const startByte = computeByteOffsetAfterLine(lines, lineEndings, startMarkerIndex);
  const endByte = computeByteOffsetAtLineStart(lines, lineEndings, endMarkerIndex);

  return bytes.subarray(startByte, endByte);
}

function computeByteOffsetAfterLine(
  lines: string[],
  lineEndings: string[],
  lineIndex: number,
): number {
  let offset = 0;
  for (let index = 0; index <= lineIndex; index += 1) {
    offset += Buffer.byteLength(lines[index] ?? "", "utf8");
    offset += Buffer.byteLength(lineEndings[index] ?? "", "utf8");
  }
  return offset;
}

function computeByteOffsetAtLineStart(
  lines: string[],
  lineEndings: string[],
  lineIndex: number,
): number {
  let offset = 0;
  for (let index = 0; index < lineIndex; index += 1) {
    offset += Buffer.byteLength(lines[index] ?? "", "utf8");
    offset += Buffer.byteLength(lineEndings[index] ?? "", "utf8");
  }
  return offset;
}

/**
 * Quick predicate: do any of the four region markers appear in the file?
 * Used to detect partial markers and choose ownership.
 */
export function hasAnyRegionMarker(bytes: Buffer): boolean {
  const text = bytes.toString("utf8");
  return (
    text.split(/\r?\n/u).some(
      (line) =>
        GENERATED_START_RE.test(line) ||
        GENERATED_END_RE.test(line) ||
        MANUAL_START_RE.test(line) ||
        MANUAL_END_RE.test(line),
    )
  );
}

export function hasAllRegionMarkers(bytes: Buffer): boolean {
  const text = bytes.toString("utf8");
  const lines = text.split(/\r?\n/u);
  return (
    lines.some((line) => GENERATED_START_RE.test(line)) &&
    lines.some((line) => GENERATED_END_RE.test(line)) &&
    lines.some((line) => MANUAL_START_RE.test(line)) &&
    lines.some((line) => MANUAL_END_RE.test(line))
  );
}

export function hasLegacyGeneratedMarker(bytes: Buffer): boolean {
  const text = bytes.toString("utf8");
  return text
    .split(/\r?\n/u)
    .some((line) => line === LEGACY_GENERATED_MARKER);
}

/**
 * Build a mixed-ownership file from a generated inner body and a manual inner
 * body. The output uses LF line endings between markers and ends with a single
 * trailing newline.
 *
 * `generatedInner` is treated as the bytes strictly between the generated
 * markers (excluding marker lines). It is emitted verbatim; callers are
 * responsible for ensuring it is LF-normalized.
 *
 * `manualInner` is the bytes strictly between the manual markers and is
 * emitted verbatim with no normalization.
 */
export function serializeMixedFile(input: {
  generatedInner: Buffer;
  manualInner: Buffer;
}): Buffer {
  const parts: Buffer[] = [
    Buffer.from(`${GENERATED_START_MARKER}\n`, "utf8"),
    input.generatedInner,
    Buffer.from(`${GENERATED_END_MARKER}\n`, "utf8"),
    Buffer.from("\n", "utf8"),
    Buffer.from(`${MANUAL_START_MARKER}\n`, "utf8"),
    input.manualInner,
    Buffer.from(`${MANUAL_END_MARKER}\n`, "utf8"),
  ];

  return Buffer.concat(parts);
}

/**
 * Replace only the generated region of an existing mixed file with a new
 * generated inner body. The manual region bytes and surrounding shape are
 * preserved byte-for-byte.
 *
 * Returns `undefined` if the existing bytes are not a valid mixed file; the
 * caller must refuse to write in that case.
 */
export function replaceGeneratedRegion(
  existing: Buffer,
  newGeneratedInner: Buffer,
): Buffer | undefined {
  const parsed = parseMixedFile(existing);
  if (!parsed.ok) return undefined;

  const text = existing.toString("utf8");
  const lines = text.split("\n");
  // Find marker line offsets in raw text.
  let cursor = 0;
  let generatedStartLineStart = -1;
  let generatedEndLineStart = -1;
  for (const line of lines) {
    const cleaned = line.endsWith("\r") ? line.slice(0, -1) : line;
    if (cleaned === GENERATED_START_MARKER && generatedStartLineStart === -1) {
      generatedStartLineStart = cursor;
    }
    if (cleaned === GENERATED_END_MARKER && generatedEndLineStart === -1) {
      generatedEndLineStart = cursor;
    }
    cursor += Buffer.byteLength(line, "utf8") + 1;
  }

  if (generatedStartLineStart === -1 || generatedEndLineStart === -1) {
    return undefined;
  }

  const startInnerByte = generatedStartLineStart +
    Buffer.byteLength(`${GENERATED_START_MARKER}\n`, "utf8");

  const before = existing.subarray(0, startInnerByte);
  const after = existing.subarray(generatedEndLineStart);

  return Buffer.concat([before, newGeneratedInner, after]);
}

/**
 * Build the generated inner bytes for a Phase 14 mixed file by stripping the
 * outer generated markers from a region-aware rendered body. Callers that
 * already render the inner body directly do not need this helper.
 */
export function ensureLfTrailingNewline(body: string): string {
  const lf = body.replace(/\r\n?/gu, "\n");
  return lf.endsWith("\n") ? lf : `${lf}\n`;
}
