// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Agent Profile Compiler contributors

import { lstat, readdir, readFile, realpath } from "node:fs/promises";
import path from "node:path";

import { containsSecretLikeLiteral } from "@agent-profile/core";

export const GENERATED_MARKDOWN_MARKER =
  "<!-- Generated by Agent Profile Compiler. Do not edit by hand. -->";

export type ArtifactFindingKind = "found" | "manual-review" | "warning";

export type ArtifactFinding = {
  kind: ArtifactFindingKind;
  path: string;
  message: string;
  generatedLooking?: boolean;
};

export type ImportClientSignals = {
  tabnine: boolean;
  codex: boolean;
  claude: boolean;
};

export type ImportAnalysisResult = {
  clients: ImportClientSignals;
  findings: ArtifactFinding[];
};

const SUPPORTED_CONFIG_PATHS = [
  "AGENTS.md",
  "CLAUDE.md",
  ".tabnine/mcp_servers.json",
  ".codex/config.toml",
  ".claude/settings.json",
  ".mcp.json",
] as const;

export async function analyzeExistingArtifacts(
  rootDir: string,
): Promise<ImportAnalysisResult> {
  const rootPath = await realpath(path.resolve(rootDir));
  const findings: ArtifactFinding[] = [];
  const clients: ImportClientSignals = {
    tabnine: false,
    codex: false,
    claude: false,
  };
  const paths = [
    ...SUPPORTED_CONFIG_PATHS,
    ...(await collectTabnineGuidelines(rootPath, findings)),
  ].sort(compareText);

  for (const relativePath of paths) {
    const source = await readOptionalText(rootPath, relativePath, findings);

    if (source === undefined) {
      continue;
    }

    applyClientSignal(relativePath, clients);
    findings.push({
      kind: "found",
      path: relativePath,
      message: `${relativePath} exists and needs manual review before generated output replaces it.`,
      generatedLooking: isGeneratedLooking(relativePath, source),
    });

    if (containsSecretLikeLiteral(source)) {
      findings.push({
        kind: "warning",
        path: relativePath,
        message: `${relativePath} contains a secret-like literal. The value was redacted.`,
      });
    }

    for (const warning of analyzeArtifactContent(relativePath, source)) {
      findings.push(warning);
    }
  }

  return {
    clients,
    findings: findings.sort(compareFindings),
  };
}

async function collectTabnineGuidelines(
  rootPath: string,
  findings: ArtifactFinding[],
): Promise<string[]> {
  const relativePath = ".tabnine/guidelines";
  const guidelineRoot = resolveArtifactPath(rootPath, relativePath);
  let entries: string[];

  try {
    const stats = await lstat(guidelineRoot);

    if (!stats.isDirectory() && !stats.isSymbolicLink()) {
      return [];
    }

    const guidelineRealPath = await realpath(guidelineRoot);

    if (!isContainedBy(rootPath, guidelineRealPath)) {
      findings.push(unsafeSymlinkFinding(relativePath));
      return [];
    }

    const guidelineRealStats = await lstat(guidelineRealPath);

    if (!guidelineRealStats.isDirectory()) {
      return [];
    }

    entries = await readdir(guidelineRealPath);
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return [];
    }

    throw error;
  }

  return entries
    .filter((entry) => entry.endsWith(".md"))
    .map((entry) => `.tabnine/guidelines/${entry}`);
}

async function readOptionalText(
  rootPath: string,
  relativePath: string,
  findings: ArtifactFinding[],
): Promise<string | undefined> {
  const artifactPath = resolveArtifactPath(rootPath, relativePath);

  try {
    const stats = await lstat(artifactPath);

    if (!stats.isFile() && !stats.isSymbolicLink()) {
      return undefined;
    }

    const artifactRealPath = await realpath(artifactPath);

    if (!isContainedBy(rootPath, artifactRealPath)) {
      findings.push(unsafeSymlinkFinding(relativePath));
      return undefined;
    }

    const artifactRealStats = await lstat(artifactRealPath);

    if (!artifactRealStats.isFile()) {
      return undefined;
    }

    return await readFile(artifactRealPath, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }

    throw error;
  }
}

function resolveArtifactPath(rootPath: string, relativePath: string): string {
  return path.join(rootPath, ...relativePath.split("/"));
}

function unsafeSymlinkFinding(relativePath: string): ArtifactFinding {
  return {
    kind: "warning",
    path: relativePath,
    message: `${relativePath} resolves outside the repository root and was not read.`,
  };
}

function applyClientSignal(
  relativePath: string,
  clients: ImportClientSignals,
): void {
  if (
    relativePath.startsWith(".tabnine/") ||
    relativePath.startsWith(".tabnine/guidelines/")
  ) {
    clients.tabnine = true;
  }

  if (relativePath === ".codex/config.toml") {
    clients.codex = true;
  }

  if (
    relativePath === "CLAUDE.md" ||
    relativePath === ".claude/settings.json" ||
    relativePath === ".mcp.json"
  ) {
    clients.claude = true;
  }
}

function analyzeArtifactContent(
  relativePath: string,
  source: string,
): ArtifactFinding[] {
  const findings: ArtifactFinding[] = [];

  if (
    (relativePath.endsWith("mcp_servers.json") ||
      relativePath === ".mcp.json") &&
    hasNonEmptyMcpServers(source)
  ) {
    findings.push({
      kind: "manual-review",
      path: relativePath,
      message: `${relativePath} contains MCP server entries. Import will not copy server definitions into ai-profile.yaml.`,
    });
  }

  if (
    relativePath === ".codex/config.toml" &&
    /mcp_servers|\[mcp/iu.test(source)
  ) {
    findings.push({
      kind: "manual-review",
      path: relativePath,
      message:
        ".codex/config.toml may contain MCP or server settings for manual review.",
    });
  }

  if (
    relativePath === ".claude/settings.json" &&
    source.includes('"defaultMode"') &&
    source.includes('"bypassPermissions"')
  ) {
    findings.push({
      kind: "warning",
      path: relativePath,
      message:
        ".claude/settings.json declares bypassPermissions. Doctor must review this before trusting runtime posture.",
    });
  }

  return findings;
}

function hasNonEmptyMcpServers(source: string): boolean {
  try {
    const value = JSON.parse(source) as unknown;
    const record = getRecord(value);
    const servers = getRecord(record?.mcpServers);
    return servers ? Object.keys(servers).length > 0 : false;
  } catch {
    return false;
  }
}

function isGeneratedLooking(relativePath: string, source: string): boolean {
  return (
    relativePath.endsWith(".md") &&
    source.replace(/\r\n?/u, "\n").split("\n")[0] === GENERATED_MARKDOWN_MARKER
  );
}

function compareFindings(
  left: ArtifactFinding,
  right: ArtifactFinding,
): number {
  return (
    compareText(left.path, right.path) ||
    compareText(left.kind, right.kind) ||
    compareText(left.message, right.message)
  );
}

function compareText(left: string, right: string): number {
  if (left < right) {
    return -1;
  }

  if (left > right) {
    return 1;
  }

  return 0;
}

function isContainedBy(rootPath: string, candidatePath: string): boolean {
  const relative = path.relative(rootPath, candidatePath);
  return (
    relative === "" ||
    (!relative.startsWith("..") && !path.isAbsolute(relative))
  );
}

function getRecord(value: unknown): Record<string, unknown> | undefined {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return undefined;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
