// Artifacts + Diff

const tree = [
  { d: 0, name: "AGENTS.md", file: true, owner: "all", status: "generated", h: "a3f1" },
  { d: 0, name: "CLAUDE.md", file: true, owner: "claude", status: "manual", h: "—" },
  { d: 0, name: ".tabnine/", dir: true },
  { d: 1, name: "guidelines/", dir: true },
  { d: 2, name: "10-sdd-workflow.md", file: true, owner: "tabnine", status: "generated", h: "8c20" },
  { d: 2, name: "20-tdd-workflow.md", file: true, owner: "tabnine", status: "generated", h: "1ed4" },
  { d: 1, name: "mcp_servers.json",  file: true, owner: "tabnine", status: "generated", h: "f0aa" },
  { d: 0, name: ".codex/",  dir: true },
  { d: 1, name: "config.toml",        file: true, owner: "codex",  status: "drifted",   h: "5b71" },
  { d: 0, name: ".agents/skills/",   dir: true },
  { d: 1, name: "sdd-change/SKILL.md", file: true, owner: "all",   status: "generated", h: "20a1" },
  { d: 1, name: "tdd-change/SKILL.md", file: true, owner: "all",   status: "generated", h: "9c34" },
  { d: 1, name: "final-review/SKILL.md", file: true, owner: "all", status: "generated", h: "ee01" },
  { d: 0, name: ".claude/skills/",   dir: true },
  { d: 1, name: "sdd-change/SKILL.md", file: true, owner: "claude", status: "generated", h: "20a1" },
  { d: 1, name: "tdd-change/SKILL.md", file: true, owner: "claude", status: "generated", h: "9c34" },
  { d: 1, name: "final-review/SKILL.md", file: true, owner: "claude", status: "generated", h: "ee01" },
];

function statusBadge(s) {
  if (s === "generated") return <span className="badge accent"><span className="dot"></span>gen</span>;
  if (s === "manual")    return <span className="badge muted"><span className="dot"></span>manual</span>;
  if (s === "drifted")   return <span className="badge warn"><span className="dot"></span>drift</span>;
  return null;
}

function ArtifactsTreePreview() {
  return (
    <div className="app">
      <TitleBar />
      <Sidebar active="artifacts" />
      <div className="workspace">
        <TopBar crumbs={["agent-profile", "artifacts"]} />
        <div className="content" style={{ display: "grid", gridTemplateColumns: "340px 1fr", gap: 14, padding: 14 }}>
          <div className="card" style={{ padding: 10 }}>
            <div className="upper muted" style={{ padding: "4px 6px 8px", display: "flex", justifyContent: "space-between" }}>
              <span>tree</span><span style={{ color: "var(--ink-4)" }}>11 files</span>
            </div>
            <div className="tree">
              {tree.map((t, i) => (
                <div key={i} className={`row ${t.name === "config.toml" ? "sel" : ""}`} style={{ paddingLeft: 6 + t.d * 14 }}>
                  <span className="indent">{t.dir ? "▾" : ""}</span>
                  <span className={`name ${t.dir ? "dir" : ""}`}>{t.name}</span>
                  {t.file && statusBadge(t.status)}
                </div>
              ))}
            </div>
          </div>
          <div className="card" style={{ padding: 0, display: "flex", flexDirection: "column" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 14px", borderBottom: "1px solid var(--line-soft)" }}>
              <span className="path">.codex/config.toml</span>
              <span className="badge warn"><span className="dot"></span>drifted</span>
              <span style={{ marginLeft: "auto", fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--ink-4)" }}>owner codex · hash 5b71</span>
            </div>
            <div style={{ padding: 14, fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--ink-2)", lineHeight: 1.7, flex: 1, whiteSpace: "pre", overflow: "auto" }}>
{`# .codex/config.toml — generated by agent-profile
# DO NOT EDIT — regenerate via \`agent-profile compile\`

profile_hash = "4c8a11e0"

[skills]
sdd_change   = ".agents/skills/sdd-change/SKILL.md"
tdd_change   = ".agents/skills/tdd-change/SKILL.md"
final_review = ".agents/skills/final-review/SKILL.md"

[safety]
mode = "guarded"
diff_before_write = true

[mcp]
mode = "local"`}
            </div>
            <div style={{ display: "flex", gap: 8, padding: "10px 14px", borderTop: "1px solid var(--line-soft)" }}>
              <button className="btn">Reveal in finder</button>
              <button className="btn">Open</button>
              <button className="btn primary">Restore from profile</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ArtifactsByTarget() {
  const cols = [
    { tgt: "Tabnine",   files: ["AGENTS.md", ".tabnine/guidelines/10-sdd-workflow.md", ".tabnine/guidelines/20-tdd-workflow.md", ".tabnine/mcp_servers.json"] },
    { tgt: "Codex",     files: ["AGENTS.md", ".codex/config.toml", ".agents/skills/sdd-change/SKILL.md", ".agents/skills/tdd-change/SKILL.md", ".agents/skills/final-review/SKILL.md"] },
    { tgt: "Claude",    files: ["CLAUDE.md", ".claude/skills/sdd-change/SKILL.md", ".claude/skills/tdd-change/SKILL.md", ".claude/skills/final-review/SKILL.md"] },
  ];
  return (
    <div className="app">
      <TitleBar />
      <Sidebar active="artifacts" />
      <div className="workspace">
        <TopBar crumbs={["agent-profile", "artifacts", "by target"]} />
        <div className="content" style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}>
            {cols.map(c => (
              <div key={c.tgt} className="card" style={{ padding: 0 }}>
                <div style={{ padding: "10px 14px", borderBottom: "1px solid var(--line-soft)", display: "flex", alignItems: "center", gap: 8 }}>
                  <span style={{ fontFamily: "var(--font-mono)", fontSize: 12, fontWeight: 600 }}>{c.tgt}</span>
                  <span className="badge ok" style={{ marginLeft: "auto" }}><span className="dot"></span>{c.files.length} files</span>
                </div>
                <div style={{ padding: 6 }}>
                  {c.files.map((f, i) => {
                    const isDrift = f === ".codex/config.toml";
                    const isManual = f === "CLAUDE.md";
                    return (
                      <div key={i} className="row" style={{ padding: "5px 8px", borderRadius: 3, fontFamily: "var(--font-mono)", fontSize: 11.5, color: "var(--ink-2)", justifyContent: "space-between" }}>
                        <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{f}</span>
                        {isDrift ? <span className="badge warn"><span className="dot"></span>drift</span>
                         : isManual ? <span className="badge muted"><span className="dot"></span>manual</span>
                         : <span className="badge accent"><span className="dot"></span>gen</span>}
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
        </div>
        <div style={{ padding: "0 14px 14px" }}>
          <div className="trust" style={{ marginTop: 4 }}>
            <div className="lock"></div>
            <div>All artifacts written to project root. Global/user-level files require explicit opt-in in Settings.</div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ArtifactsTab() {
  return (
    <div className="page">
      <div className="page-intro">
        <h2>Generated artifacts</h2>
        <p>Tree-and-preview is the default; the by-target columnar view answers "what does Codex actually see?" without making the user pivot in their head.</p>
        <p className="pencil">↳ generated · manual · drifted — three states, never four.</p>
      </div>
      <div className="variants">
        <Sketch label="A — Tree + preview" sub="ide-feel · scoped" width={1100}
          scribbles={[
            { text: "drift surfaces here, not buried", top: 110, right: -50, rot: 5, w: 200 },
            { text: "preview is read-only — write happens via diff", bottom: 50, left: -30, rot: -4, w: 240 },
          ]}>
          <ArtifactsTreePreview />
        </Sketch>
        <Sketch label="B — By target" sub="three columns · scan-friendly" width={1100}>
          <ArtifactsByTarget />
        </Sketch>
      </div>
    </div>
  );
}

// ============ DIFF ============

function DiffSplit() {
  return (
    <div className="app">
      <TitleBar />
      <Sidebar active="diff" />
      <div className="workspace">
        <TopBar crumbs={["agent-profile", "diff"]} />
        <div className="content" style={{ display: "grid", gridTemplateColumns: "300px 1fr", gap: 14 }}>
          <div className="card" style={{ padding: 8 }}>
            <div className="upper muted" style={{ padding: "4px 6px 8px" }}>pending writes · 4</div>
            {[
              { f: ".tabnine/guidelines/10-sdd-workflow.md", st: "M", c: "var(--warn)" },
              { f: ".codex/config.toml",                     st: "M", c: "var(--warn)" },
              { f: ".claude/skills/sdd-change/SKILL.md",     st: "A", c: "var(--ok)" },
              { f: "AGENTS.md",                              st: "M", c: "var(--warn)" },
            ].map((r,i) => (
              <div key={i} className={`row ${i===0?"sel":""}`} style={{ padding: "5px 8px", borderRadius: 3, fontFamily: "var(--font-mono)", fontSize: 11.5, color: "var(--ink-2)", background: i===0?"var(--accent-bg)":"transparent" }}>
                <span style={{ color: r.c, width: 14, fontWeight: 600 }}>{r.st}</span>
                <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", flex: 1 }}>{r.f}</span>
                <input type="checkbox" defaultChecked style={{ accentColor: "var(--accent)" }} />
              </div>
            ))}
            <div style={{ marginTop: 12, padding: 10, border: "1px solid oklch(0.5 0.1 80 / 0.4)", background: "oklch(0.4 0.08 80 / 0.10)", borderRadius: 4, fontSize: 11, color: "var(--ink-2)" }}>
              <span className="badge warn"><span className="dot"></span>manual edit</span>
              <div style={{ marginTop: 6, lineHeight: 1.5 }}><span className="path">.codex/config.toml</span> has manual edits. Writing will overwrite them.</div>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 6, marginTop: 12 }}>
              <button className="btn primary">Write selected (3)</button>
              <button className="btn">Write all (4)</button>
              <button className="btn ghost">Cancel</button>
            </div>
          </div>
          <div className="diff">
            <div className="file-h">
              <span className="path">.tabnine/guidelines/10-sdd-workflow.md</span>
              <span className="badge warn"><span className="dot"></span>modified</span>
              <span style={{ marginLeft: "auto", color: "var(--ink-4)", fontFamily: "var(--font-mono)", fontSize: 10 }}>+8 −3</span>
            </div>
            <div>
              <div className="hunk ctx"><div className="ln">12</div><div className="ln">12</div><div className="code">## SDD workflow</div></div>
              <div className="hunk ctx"><div className="ln">13</div><div className="ln">13</div><div className="code"></div></div>
              <div className="hunk del"><div className="ln">14</div><div className="ln"></div><div className="code">Always run tests before committing.</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">14</div><div className="code">Always run `npm test` and `mvn test` before committing.</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">15</div><div className="code">Use Playwright for end-to-end checks.</div></div>
              <div className="hunk ctx"><div className="ln">15</div><div className="ln">16</div><div className="code"></div></div>
              <div className="hunk ctx"><div className="ln">16</div><div className="ln">17</div><div className="code">### Skill: sdd-change</div></div>
              <div className="hunk del"><div className="ln">17</div><div className="ln"></div><div className="code">- specify-design-develop</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">18</div><div className="code">- specify → design → develop → review</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">19</div><div className="code">- safety mode: guarded</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">20</div><div className="code">- profile_hash: 4c8a11e0</div></div>
              <div className="hunk ctx"><div className="ln">18</div><div className="ln">21</div><div className="code"></div></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function DiffFullBleed() {
  return (
    <div className="app">
      <TitleBar />
      <Sidebar active="diff" />
      <div className="workspace">
        <div style={{ display: "flex", gap: 6, padding: "10px 16px", borderBottom: "1px solid var(--line-soft)", overflowX: "auto" }}>
          {[
            { f: "AGENTS.md", st: "M" },
            { f: ".tabnine/.../10-sdd.md", st: "M", on: true },
            { f: ".codex/config.toml", st: "M", warn: true },
            { f: ".claude/.../sdd-change/SKILL.md", st: "A" },
          ].map((t,i) => (
            <button key={i} className={`btn ${t.on?"primary":""}`} style={{ fontSize: 11 }}>
              <span style={{ color: t.warn ? "var(--warn)" : (t.on ? "inherit" : "var(--ink-3)") }}>{t.st}</span>
              <span>{t.f}</span>
            </button>
          ))}
          <div style={{ flex: 1 }}></div>
          <button className="btn">Write all (4)</button>
          <button className="btn primary">Write selected (3)</button>
        </div>
        <div className="content" style={{ padding: 14 }}>
          <div className="diff">
            <div className="file-h">
              <span className="path">.tabnine/guidelines/10-sdd-workflow.md</span>
              <span className="badge warn"><span className="dot"></span>modified</span>
              <span className="badge ok"><span className="dot"></span>generated</span>
              <span style={{ marginLeft: "auto", color: "var(--ink-4)", fontFamily: "var(--font-mono)", fontSize: 10 }}>+8 −3 · diff before write</span>
            </div>
            <div>
              <div className="hunk ctx"><div className="ln">12</div><div className="ln">12</div><div className="code">## SDD workflow</div></div>
              <div className="hunk ctx"><div className="ln">13</div><div className="ln">13</div><div className="code"></div></div>
              <div className="hunk del"><div className="ln">14</div><div className="ln"></div><div className="code">Always run tests before committing.</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">14</div><div className="code">Always run `npm test` and `mvn test` before committing.</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">15</div><div className="code">Use Playwright for end-to-end checks.</div></div>
              <div className="hunk ctx"><div className="ln">15</div><div className="ln">16</div><div className="code"></div></div>
              <div className="hunk ctx"><div className="ln">16</div><div className="ln">17</div><div className="code">### Skill: sdd-change</div></div>
              <div className="hunk del"><div className="ln">17</div><div className="ln"></div><div className="code">- specify-design-develop</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">18</div><div className="code">- specify → design → develop → review</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">19</div><div className="code">- safety mode: guarded</div></div>
              <div className="hunk add"><div className="ln"></div><div className="ln">20</div><div className="code">- profile_hash: 4c8a11e0</div></div>
              <div className="hunk ctx"><div className="ln">18</div><div className="ln">21</div><div className="code"></div></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function DiffTab() {
  return (
    <div className="page">
      <div className="page-intro">
        <h2>Diff preview</h2>
        <p>Diff-before-write is the safety contract. The split view scans best for many files; the full-bleed view focuses attention when reviewing one. Manual edits surface a warning so the user always knows when their hand-edits are about to be overwritten.</p>
      </div>
      <div className="variants">
        <Sketch label="A — File list + pane" sub="default · checkboxes for selective write" width={1100}
          scribbles={[
            { text: "manual-edit warning lives here, never hidden", top: 250, left: -40, rot: -4, w: 210 },
            { text: "every write is opt-in — never automatic", bottom: 30, right: -40, rot: 4, w: 220 },
          ]}>
          <DiffSplit />
        </Sketch>
        <Sketch label="B — Tabbed full-bleed" sub="focus mode · one file at a time" width={1100}>
          <DiffFullBleed />
        </Sketch>
      </div>
    </div>
  );
}

Object.assign(window, { ArtifactsTab, DiffTab });
