// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Agent Profile Compiler contributors

import type { Phase14ImportFileFinding } from "@agent-profile/compiler";

// Phase 16: deciding which actions to offer on a row is the safety-critical
// bit of the FileActionRow component. We keep it in a pure module so unit
// tests can exercise it without a Svelte runtime.
//
// The spec rules baked into this function:
// - `Replace generated-owned` is offered only for files Phase 14 classifies
//   as `generated-owned`. It is never offered for `unknown`, `manual-owned`,
//   or local runtime files.
// - `Add regions` is offered only for unmarked supported root-instruction
//   files. Already-mixed files get `Update generated region` instead.
// - Refused conflict rows can only `Skip`.
// - Local-runtime / ignored rows can only `Preserve` or `Skip`.
// - Actions that require compiled generated bytes are hidden when there
//   is no `ai-profile.yaml` to compile from — the plan endpoint would
//   refuse them anyway and the UI should not advertise dead options.

export type SelectedAction =
  | "preserve"
  | "add-regions"
  | "update-generated-region"
  | "replace-generated-owned"
  | "skip";

export type OfferedActionsContext = {
  /**
   * Whether `ai-profile.yaml` is present in the project root. When false,
   * actions that require compiled generated bytes (`add-regions`,
   * `update-generated-region`, `replace-generated-owned`) are hidden.
   * Defaults to true so callers that have not yet wired profile detection
   * do not regress.
   */
  profileFound?: boolean;
};

export function offeredActions(
  finding: Phase14ImportFileFinding,
  context: OfferedActionsContext = {},
): SelectedAction[] {
  const profileFound = context.profileFound ?? true;

  if (finding.action === "refuse-conflict") {
    return ["skip"];
  }
  if (finding.action === "ignore-local-runtime") {
    return ["preserve", "skip"];
  }

  if (finding.kind !== "root-instructions") {
    const offers: SelectedAction[] = ["preserve", "skip"];
    if (profileFound && finding.ownership === "generated-owned") {
      offers.push("replace-generated-owned");
    }
    if (profileFound && finding.ownership === "mixed") {
      offers.push("update-generated-region");
    }
    return offers;
  }

  // root-instructions
  if (finding.action === "create") {
    return ["preserve", "skip"];
  }
  if (
    finding.action === "update-generated-region" ||
    finding.ownership === "mixed"
  ) {
    if (profileFound) {
      return ["preserve", "update-generated-region", "skip"];
    }
    return ["preserve", "skip"];
  }
  // unmarked existing root-instructions file
  if (profileFound) {
    return ["preserve", "add-regions", "skip"];
  }
  return ["preserve", "skip"];
}

export function defaultActionFor(
  finding: Phase14ImportFileFinding,
  context: OfferedActionsContext = {},
): SelectedAction {
  const profileFound = context.profileFound ?? true;
  switch (finding.action) {
    case "create":
      return "preserve";
    case "insert-regions":
      // Without a profile the plan endpoint refuses add-regions; default
      // to preserve so the user sees a runnable plan on first build.
      return profileFound ? "add-regions" : "preserve";
    case "update-generated-region":
      return profileFound ? "update-generated-region" : "preserve";
    case "preserve":
      return "preserve";
    case "ignore-local-runtime":
      return "preserve";
    case "refuse-conflict":
      return "skip";
  }
}

export function isReplaceUnsafe(action: SelectedAction): boolean {
  return action === "replace-generated-owned";
}
